### ISSUE TITLE
.ts sources should not be published to npm

### ISSUE THREAD

**Issue by justinfagnani** [apollo-elements/apollo-elements#101]
## Package
`@apollo-elements/components`

## Description
Importing `@apollo-elements/components/apollo-client.js'` causes a ton of TypeScript errors when building my project.

Example:
```
node_modules/@apollo-elements/components/apollo-client.ts:215:12 - error TS2790: The operand of a 'delete' operator must be optional.

215     delete target.client;
               ~~~~~~~~~~~~~


Found 53 errors.
```

What's very unusual about this is that the errors are reported on apollo-element's own `.ts` files, which shouldn't be included in the compilation unit for my project. Adding `"skipLibCheck": true` or `"exclude": ["node_modules"]` does not remove the errors.

What appears to be the cause is that `@apollo-elements/components` publishes the .ts sources alongside the .js/.d.ts files, causing the TypeScript compiler to pick up these files when imported.

According to the TypeScript team, these files should not be published to npm. See: https://github.com/microsoft/TypeScript/issues/22228#issuecomment-370095042

Note, on the Lit team we _do_ publish .ts files to improve the source-map experience, but we do so by compiling all .ts files from a /src directory so they are not available at the same path as the compiler output.

## Steps To Reproduce
1. `npm i @apollo-elements/components`
2. `import '@apollo-elements/components/apollo-client.js';`
3. `tsc`
4. See errors

## Expected Behavior
No errors

**Comment by bennypowers** [comment]
interesting. I'm doing this as you said to improve sourcemap support. See https://github.com/apollographql/apollo-client/issues/6921#issuecomment-696933521

I'm open to suggestions. I'd prefer not to ship `/dist/`, but if it comes down to it I might have to

do try
```
 - @apollo-elements/components@1.3.0-alpha.1
 - @apollo-elements/fast@1.2.0-alpha.1
 - @apollo-elements/gluon@3.2.0-alpha.1
 - @apollo-elements/haunted@1.1.0-alpha.1
 - @apollo-elements/hybrids@3.4.0-alpha.1
 - @apollo-elements/interfaces@1.4.0-alpha.1
 - @apollo-elements/lib@3.5.0-alpha.1
 - @apollo-elements/lit-apollo@3.2.0-alpha.1
 - @apollo-elements/mixins@3.4.0-alpha.1
 - @apollo-elements/polymer@3.3.0-alpha.1
 ```
which has support for ts strict mode, and LMK
