### ISSUE TITLE
How to use provide client to lit-apollo?

### ISSUE THREAD

**Issue by superchris** [apollo-elements/apollo-elements#106]
## Description
It's not clear from reading the documentation how to provide the client to a lit-apollo element

**Comment by bennypowers** [comment]
Hi @superchris, thanks for opening the issue.

You have a few options for assigning the client instance. Please take a look at https://apolloelements.dev/guides/getting-started/apollo-client/

FWIW, in typical SPA scenarios I tend to just use the global `window.__APOLLO_CLIENT__`, which doesn't require any config.

**Comment by bennypowers** [comment]
See https://apolloelements.dev/api/libraries/lit-apollo/apollo-query/#client
