### ISSUE TITLE
Add standard-version (or something else)

### ISSUE THREAD

**Issue by LasaleFamine** [apollo-elements/apollo-elements#12]
What do you think to add a tool for writing changelogs with commits? I usually use [standard-version](https://github.com/conventional-changelog/standard-version)

**Comment by bennypowers** [comment]
It's a good idea. Maybe commitizen hooks. I'll going to do a little reading then get back to you.

**Comment by bennypowers** [comment]
I'm strongly considering integrating [`lerna-semantic-release`](https://github.com/atlassian/lerna-semantic-release). This comment is just to track my thinking on the issue so far.

There's some pain which is holding back immediate adoption:
- I've had trouble running pre-commit hooks via atom's `github` git UI in the past
- requires fairly extensive changes to CI/CD. Coming from a background with gitlab-ci, I wasn't so impressed with travis, and might give circle-ci a go.

**Comment by TimPietrusky** [comment]
I've been using semantic-release for a few projects now (not mono repos) and I like it super much. Using it in combination with travis, but any other CI service should do too. Interested on what you will find out.
