### ISSUE TITLE
Option to extends lit-apollo mixins from another base

### ISSUE THREAD

**Issue by abdonrd** [apollo-elements/apollo-elements#125]
I was checking to use lit-apollo with the [IBM/pwa-lit-template](https://github.com/IBM/pwa-lit-template), but we have a PageElement base class: https://github.com/IBM/pwa-lit-template/blob/main/src/helpers/page-element.ts

Is there an option for `ApolloQuery` to extend from `PageElement` instead of `LitElement`?

**Comment by bennypowers** [comment]
Yes, you can.

See https://github.com/apollo-elements/pwa-lit-template/tree/apollo-query-mixin

```
git clone git@github.com/apollo-elements/pwa-lit-template
cd pwa-lit-template
npm ci
npm start
```

Just note that you'll have to hook up the reactivity and typings yourself.

https://github.com/apollo-elements/pwa-lit-template/blob/d4c2512056d50300b7dd6e932158ae2d1dab0634/src/pages/page-home.ts#L11-L62

If you'd prefer not to have to do that work, You might consider making `PageElement` a mixin and extending from `ApolloQuery` from `@apollo-elements/query`. That's what I do at work when I want to share behaviours. Really at the end of the day though, it's six of one, half a dozen of the other, so you could create a `LitApolloQueryMixin` which applies `ApolloQueryMixin` and implements the interface like you see in https://github.com/apollo-elements/apollo-elements/blob/master/packages/lit-apollo/apollo-element.ts and https://github.com/apollo-elements/apollo-elements/blob/master/packages/lit-apollo/apollo-query.ts
