### ISSUE TITLE
Version using the new ReactiveController from Lit v2

### ISSUE THREAD

**Issue by abdonrd** [apollo-elements/apollo-elements#126]
There are any plan to create a version based on ReactiveController from Lit v2?

https://github.com/Polymer/lit-html/blob/lit-next/packages/reactive-element/src/reactive-controller.ts

Another references:
- https://github.com/Polymer/lit-html/pull/1563
- https://github.com/Polymer/lit-html/tree/lit-next/packages/labs/task

**Comment by bennypowers** [comment]
Definitely something we're looking into

**Comment by abdonrd** [comment]
Interesting decorator: https://github.com/Polymer/lit-html/pull/1767

**Comment by bennypowers** [comment]
This is done. Only thing blocking release is the docs

**Comment by abdonrd** [comment]
Nice! Thanks @bennypowers! Waiting for docs and https://github.com/modernweb-dev/web/issues/1376#issuecomment-831128623 to try it!
