### ISSUE TITLE
Why graphql-code-generator recomendation instead of apollo client:codegen?

### ISSUE THREAD

**Issue by abdonrd** [apollo-elements/apollo-elements#127]
Why `graphql-code-generator` recomendation instead of `apollo client:codegen`?

Just curious why not recommend the official Apollo CLI.

Thanks!

**Comment by bennypowers** [comment]
You know what they say "write what you know"

If you have a set up that works with Apollo CLI and want to write about it in the guides section, send a PR I'm happy to review 🙂
