### ISSUE TITLE
Module packages should have file extensions in imports

### ISSUE THREAD

**Issue by davidkudera** [apollo-elements/apollo-elements#144]
## Package
`@apollo-elements/components`

Didn't try others but they are probably same.

## Description
Module packages should internally use fully specified imports. For example this line of code https://github.com/apollo-elements/apollo-elements/blob/321cfddadfd7d54c5da51f3c84361317d096421e/packages/components/index.ts#L1 should be written as 

```
export * from './apollo-client.js';
```

... even in ts environment.

Trying `import '@apollo-elements/components/apollo-client'` in newer Webpack (version 5 and up) will throw errors otherwise:

```
ERROR in ./node_modules/@apollo-elements/lib/create-apollo-client.js 2:0-54
Module not found: Error: Can't resolve './has-all-variables' in 'C:\***\node_modules\@apollo-elements\lib'
Did you mean 'has-all-variables.js'?
BREAKING CHANGE: The request './has-all-variables' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

The same goes for the automagically resolved `index` files:

```
ERROR in ./node_modules/@apollo-elements/lib/create-apollo-client.js 1:0-88
Module not found: Error: Can't resolve '@apollo/client/core' in 'C:\***\node_modules\@apollo-elements\lib'
Did you mean 'index.js'?
BREAKING CHANGE: The request '@apollo/client/core' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

Loading the package from Skypack does not work either:

```
[Package Error] "@apollo-elements/components@v1.4.0" could not be built. 
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
[3/5] Building package using esinstall…
Running esinstall...
Running esinstall...
Running esinstall...
404 Not Found - GET https://registry.npmjs.org/@apollo-elements%2ftest-helpers - Not found

---

Uncaught Error: [Package Error] "@apollo-elements/components@v1.4.0" could not be built.
```

but I'm not sure if these two are related or not.

My workaround for Webpack is using custom `module.rules` configuration for `.js` files:

```js
{
  test: /\.js$/,
  resolve: {
    fullySpecified: false
  }
}
```

## Steps To Reproduce
https://github.com/davidkudera/apollo-elements-webpack-repro

1. Run `npm run build` or `npm start`

The workaround is included here: https://github.com/davidkudera/apollo-elements-webpack-repro/blob/master/webpack.config.js#L25-L32

## Expected Behavior
Webpack (and maybe Skypack and other) users should not have to encounter these errors.

## Browser and Version
* Chrome 91.0.4472.77
* Webpack 5.38.1

**Comment by bennypowers** [comment]
👋 Hi @davidkudera thanks for opening this issue.

PTAL at https://github.com/apollo-elements/apollo-elements/projects/2

There's a card there for adding .js to imports.

I'll reference this issue in the project as well.

**Comment by bennypowers** [comment]
Try this out on [next](https://www.npmjs.com/package/@apollo-elements/components/v/2.0.0-next.0)

Docs @ [next.apolloelements.dev](https://next.apolloelements.dev)

Beware breaking changes - see CHANGELOG
