### ISSUE TITLE
ApolloQueryController with pollInterval does not unsubscribe

### ISSUE THREAD

**Issue by ba55ie** [apollo-elements/apollo-elements#192]
## Package
`@apollo-elements/core`

## Description

Recently I upgraded our code base from the old `@apollo-elements/lit-apollo` base Classes to plain LitElements using the new Controllers. 🎉 

That went very smoothly and the only difference I found after the upgrade is that using a `ApolloQueryController` with a `pollInterval` keeps on polling after the component has been destroyed.

## Steps To Reproduce

Our repo is private, so I provide some dummy code.

```typescript
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { ApolloQueryController } from '@apollo-elements/core';

import { MyQuery} from './my-query';
import { apolloClient } from './my-client';

@customElement('my-component')
export class MyComponent extends LitElement {
    @property()
    foo: string;

    #query = new ApolloQueryController(this, MyQuery, {
        client: apolloClient,

        pollInterval: 60 * 1000 * 5, // 5 minutes

        variables: {
            bar: 'baz',
        },

        onData: (data) => {
          this.foo = data.foo;
        },
    });

    override render() {
        return html`<h1>${this.foo}</h1>`;
    }
}
```

## Expected Behavior
I expected the query to stop polling after the component had been destroyed.

## Additional Info
I could fix it by using `noAutoSubscribe` and (un)subscribing manually. I also looked at the `startPolling` and `stopPolling` methods. The drawback of `startPolling` is that it causes a double request when called in the `connectedCallback` with `noAutoSubscribe: false` and a delay when `true`.

The working code:

```typescript
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { ApolloQueryController } from '@apollo-elements/core';

import { MyQuery} from './my-query';
import { apolloClient } from './my-client';

import type { ObservableSubscription } from '@apollo/client/core';

@customElement('my-component')
export class MyComponent extends LitElement {
    @property()
    foo: string;

    #query = new ApolloQueryController(this, MyQuery, {
        client: apolloClient,

        noAutoSubscribe: true,

        pollInterval: 60 * 1000 * 5, // 5 minutes

        variables: {
            bar: 'baz',
        },

        onData: (data) => {
          this.foo = data.foo;
        },
    });

    #subscription: ObservableSubscription;

    override render() {
        return html`<h1>${this.foo}</h1>`;
    }

    override connectedCallback() {
        super.connectedCallback();

        this.#subscription = this.#query.subscribe();
    }

    override disconnectedCallback() {
        this.#subscription?.unsubscribe();

        super.disconnectedCallback();
    }
}
```

**Comment by ba55ie** [comment]
It could also be just a documentation issue. It's quite hard to understand the differences between the `pollInterval`, `start/stopPolling`, Queries and Subscriptions. In our case the server does not support Subscriptions yet.

**Comment by bennypowers** [comment]
So if i understood the issue, you expect the query controller to call `this.stopPolling()` in `hostDisconnected`, right? That seems reasonable to me.

I also noticed a problem with the docs site not showing the correct options object for controllers, i'll look in to that.

**Comment by bennypowers** [comment]
@ba55ie try with `@apollo-elements/core@1.0.1-next.0`

**Comment by ba55ie** [comment]
> @ba55ie try with `@apollo-elements/core@1.0.1-next.0`

This works like a charm! 🎉
