### ISSUE TITLE
Add support to GraphQL v16

### ISSUE THREAD

**Issue by abdonrd** [apollo-elements/apollo-elements#204]
Right now it doesn't work:

<img width="585" alt="Screenshot 2021-11-23 at 10 52 56" src="https://user-images.githubusercontent.com/1007051/143003246-6656719d-03b4-4cc6-8e67-e4fc9500bbd5.png">

For reference, `@apollo/client` did it here: https://github.com/apollographql/apollo-client/pull/8997

**Comment by abdonrd** [comment]
Also when we update the project from `@apollo/client` v3.4 to v3.5:

<img width="1010" alt="Screenshot 2021-11-23 at 10 59 46" src="https://user-images.githubusercontent.com/1007051/143004363-1a3073c3-0949-4359-bef0-e7af01bde992.png">

**Comment by bennypowers** [comment]
huh! did ac drop ZenObservable?

**Comment by abdonrd** [comment]
> huh! did ac drop ZenObservable?

I see this: https://github.com/apollographql/apollo-client/pull/8695

**Comment by bennypowers** [comment]
ok so it should be a relatively straightforward fix: `import type {} from 'zen-observable-ts'` in files that use it (or, even better, use a type derived from ac types without referencing transitive deps)

I don't have time to work on this immediately, but i'm happy to review a PR
