### ISSUE TITLE
@apollo-elements/create does not install dependency

### ISSUE THREAD

**Issue by niklaushug** [apollo-elements/apollo-elements#211]
## Package
`@apollo-elements/create`

## Description
By using `npm init @apollo-elements` with all default flags I would expect to have all dependencies installed.

## Steps To Reproduce
1. Open terminal
2. Run `npm init @apollo-elements`
3. Ensure that question `Install dependencies?` is answered with `Yes` (`Yes` is default)
4. Run `ls` and see that folder `node_modules` does not exist
5. Run `npm install`
6. Run `ls` and see that folder `node_modules` exist

## Expected Behaviour
I expect to have a `node_modules` folder in my current working directory with a lot of dependencies in it after running `npm init @apollo-elements`. 

## Additional Info
- @apollo-elements/create@3.1.0 was installed by npm
- Used npm version: 7.19.1 and v8.1.2
- Used Node version: v16.5.0 and v16.13.1

**Comment by bennypowers** [comment]
Thanks for the report @niklaushug.

Did you by chance notice the generator hanging after "Scaffolding App Files..."?

**Comment by bennypowers** [comment]
I just now published [@apollo-elements/create v3.1.1](https://www.npmjs.com/package/@apollo-elements/create) under the `latest` dist tag. Can you please try again (and check #212 as well)?


You may need to delete your npx cache to get the latest version when running `npm init @apollo-elements`

```
rm -rf ~/.npm/_npx
```
on POSIX-compatible systems

**Comment by niklaushug** [comment]
> Did you by chance notice the generator hanging after "Scaffolding App Files..."?

Yes, it was hanging with subsequent message.

```
Scaffolding App Files...
Done!
```
I was waiting for a few minutes but nothing happened after.

> Can you please try again?

I just executed `npm init @apollo-elements` and I got a running app (@apollo-elements/create@3.1.2 was used). It was not necessary to delete npx cache.

Thanks a lot.
