### ISSUE TITLE
[Security] Workflow pull-request.yml is using vulnerable action paambaati/codeclimate-action

### ISSUE THREAD

**Issue by fockboi-lgtm** [apollo-elements/apollo-elements#216]
The workflow pull-request.yml is referencing action paambaati/codeclimate-action using references v2.7.3. However this reference is missing the commit [62e5eab9c1f8c952f64862c152e205c9c835b755](https://github.com/paambaati/codeclimate-action/commits/62e5eab9c1f8c952f64862c152e205c9c835b755) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by bennypowers** [comment]
https://github.com/apollo-elements/apollo-elements/blob/d89fa44f0247148846ac2ccda80989e4ad781709/.github/workflows/pull-request.yml#L38
