### ISSUE TITLE
Apollo Elements Bug

### ISSUE THREAD

**Issue by LasseRosenow** [apollo-elements/apollo-elements#219]
## Package
`@apollo-elements/core`

## Description
Autocomplete for variables in controllers is not working:

![image](https://user-images.githubusercontent.com/10547444/148657250-c82bc82d-3893-4226-a574-622b72809f12.png)

As you can see, it is not detecting the variables from the TypedDocumentNode. The generics implementation seems to have some issues here.

## Steps To Reproduce
```typescript
interface User {
  id: number;
  name: string;
  picture?: string;
}

export const UsersQuery: TypedDocumentNode<{ users: User[] }, { name: string }> = gql`
query Users {
  users {
    id
    name
    picture
  }
}
`;

const profile = new ApolloQueryController(this, UsersQuery, {
  variables: {},
});
```

**Comment by LasseRosenow** [comment]
The issue is here: https://github.com/apollo-elements/apollo-elements/blob/602a22bdc73749696e94ed39b46d43fc0d87aa61/packages/core/apollo-query-controller.ts#L100

If I replace the query variable type `ComponentDocument<D>` with `TypedDocumentNode<D, V>` it works.
The issue with `ComponentDocument<D>` is, that it ignores the V generic type and so the variables in the option property don't know their type.

**Comment by bennypowers** [comment]
I started on a fix. TBH the type system here was kind of held together with duct tape. Should be much nicer when I get a minute to fix it

**Comment by bennypowers** [comment]
@LasseRosenow can you try with the versions listed in https://github.com/apollo-elements/apollo-elements/pull/224 and let me know?

**Comment by LasseRosenow** [comment]
This issue seems to be fixed now :) I just switched my simple controllers implementation with yours and it works the same :) Thank you very much :)

But now as I started replacing some more places in my code, I get a new error, when lazily creating the controllers. Because some of my controllers depend on web component properties, which need to be initialized first, so I have to create the controller in `firstUpdated` etc.

I get a weird error then :(

I opened an issue regarding this: #225
