### ISSUE TITLE
Apollo Elements Bug - Cannot lazily initialize query controllers

### ISSUE THREAD

**Issue by LasseRosenow** [apollo-elements/apollo-elements#225]
## Package
﻿

`@apollo-elements/core`

## Description
If I initialize the my ApolloQueryController when creating the class property, everything works fine, but as soon as I cannot initialize the ApolloQueryController straightaway (because I need to wait for a property to be initialized first), I get an error.

```typescript

@customElement("app-page")
export class AppPage extends LitElement {
  @property() pageId: string | null = null;

  query: ApolloQueryController<PageByIdQuery, PageByIdQueryVariables> | null = null;

  firstUpdated(): void {
    if (this.pageId !== null) {
      this.query = new ApolloQueryController(this, PageByIdDocument, {
        variables: {
          id: this.pageId,
        },
      });
    }
  }

  render() {}
}

```

As soon as I create the controller within the firstUpdated method, I get this error:
```
tslib.es6.js:230 Uncaught (in promise) TypeError: Cannot read private member from an object whose class did not declare it
    at __classPrivateFieldGet (tslib.es6.js:230:94)
    at ApolloQueryController.hostConnected (apollo-query-controller.ts:109:9)
    at AppPage.addController (reactive-element.ts:867:31)
    at new ApolloController (apollo-controller.ts:154:23)
    at new ApolloQueryController (apollo-query-controller.ts:102:5)
    at AppPage.firstUpdated (app-page.ts:23:20)
    at AppPage._$didUpdate (reactive-element.ts:1244:12)
    at AppPage.performUpdate (reactive-element.ts:1229:12)
    at AppPage.scheduleUpdate (reactive-element.ts:1148:17)
    at AppPage.__enqueueUpdate (reactive-element.ts:1120:25)
```

## Steps To Reproduce

1. Example is above :)

## Expected Behavior
It should just work.

## Browser and Version

Chrome 97

**Comment by bennypowers** [comment]
Thanks, are you getting this in the dev server or a production build? How did you scaffold your app?

**Comment by bennypowers** [comment]
Minimal repro:
https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudCwgUmVhY3RpdmVDb250cm9sbGVyLCBSZWFjdGl2ZUNvbnRyb2xsZXJIb3N0fSBmcm9tICdsaXQnO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuXG5cbmNsYXNzIFN1cENvbnQgaW1wbGVtZW50cyBSZWFjdGl2ZUNvbnRyb2xsZXIge1xuICBjb25zdHJ1Y3Rvcihwcml2YXRlIGhvc3Q6IFJlYWN0aXZlQ29udHJvbGxlckhvc3QpIHtcbiAgICBob3N0LmFkZENvbnRyb2xsZXIodGhpcyk7XG4gIH1cbiAgXG4gIGhvc3RDb25uZWN0ZWQoKSB7XG4gICAgY29uc29sZS5sb2coJ3N1cGVyIGhvc3RDb25uZWN0ZWQnKTtcbiAgfVxufVxuXG5jbGFzcyBDb250IGV4dGVuZHMgU3VwQ29udCB7XG4gICNoYXNEaXNjb25uZWN0ZWQgPSBmYWxzZTtcbiAgY29uc3RydWN0b3IoXG4gICAgaG9zdDogUmVhY3RpdmVDb250cm9sbGVySG9zdCxcbiAgKSB7XG4gICAgc3VwZXIoaG9zdCk7XG4gIH1cblxuICBvdmVycmlkZSBob3N0Q29ubmVjdGVkKCk6IHZvaWQge1xuICAgIHN1cGVyLmhvc3RDb25uZWN0ZWQoKTtcbiAgICBpZiAodGhpcy4jaGFzRGlzY29ubmVjdGVkKSB7XG4gICAgICB0aGlzLiNoYXNEaXNjb25uZWN0ZWQgPSBmYWxzZTtcbiAgICB9XG4gIH1cbn1cblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BwIHsgY29sb3I6IGJsdWUgfWA7XG5cbiAgQHByb3BlcnR5KClcbiAgbmFtZSA9ICdTb21lYm9keSc7XG5cbiAgY29ubmVjdGVkQ2FsbGJhY2soKSB7XG4gICAgc3VwZXIuY29ubmVjdGVkQ2FsbGJhY2soKTtcbiAgICB0aGlzLmNvbnQgPSBuZXcgQ29udCh0aGlzKTtcbiAgfVxuICBcbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYDxwPkhlbGxvLCAke3RoaXMubmFtZX0hPC9wPmA7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nIG5hbWU9XCJXb3JsZFwiPjwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ

```ts
import {html, css, LitElement, ReactiveController, ReactiveControllerHost} from 'lit';
import {customElement, property} from 'lit/decorators.js';


class SupCont implements ReactiveController {
  constructor(private host: ReactiveControllerHost) {
    host.addController(this);
  }
  
  hostConnected() {
    console.log('super hostConnected');
  }
}

class Cont extends SupCont {
  #hasDisconnected = false;
  constructor(
    host: ReactiveControllerHost,
  ) {
    super(host);
  }

  override hostConnected(): void {
    super.hostConnected();
    if (this.#hasDisconnected) {
      this.#hasDisconnected = false;
    }
  }
}

@customElement('simple-greeting')
export class SimpleGreeting extends LitElement {
  static styles = css`p { color: blue }`;

  @property()
  name = 'Somebody';

  connectedCallback() {
    super.connectedCallback();
    this.cont = new Cont(this);
  }
  
  render() {
    return html`<p>Hello, ${this.name}!</p>`;
  }
}
```

**Comment by bennypowers** [comment]
I believe that this is an upstream issue with lit, or (more likely) tslib: https://github.com/lit/lit/issues/2446

in the mean time I suggest that you instantiate the controller as a field (like the examples in the docs) but use `shouldSubscribe` or `noAutoSubscribe` to prevent automatic fetching until you're ready:

[playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudCwgUHJvcGVydHlWYWx1ZXN9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbmltcG9ydCB7IEFwb2xsb1F1ZXJ5Q29udHJvbGxlciB9IGZyb20gJ0BhcG9sbG8tZWxlbWVudHMvY29yZSc7XG5cbmltcG9ydCB7IGdxbCwgVHlwZWREb2N1bWVudE5vZGUgfSBmcm9tICdAYXBvbGxvL2NsaWVudC9jb3JlJztcblxuaW1wb3J0ICdAYXBvbGxvLWVsZW1lbnRzL2NvbXBvbmVudHMvYXBvbGxvLWNsaWVudC5qcyc7XG5cbmNvbnN0IFBhZ2VCeUlkRG9jdW1lbnQ6IFR5cGVkRG9jdW1lbnROb2RlPHsgaGV5OiAnaGknIH0sIHsgaWQ6IHN0cmluZyB9PiA9IGdxbGBcbiAgICBxdWVyeSgkaWQ6IFN0cmluZykge1xuICAgICAgaGV5KGlkOiAkaWQpXG4gICAgfVxuICAgYDtcblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgQHByb3BlcnR5KCkgcGFnZUlkOiBzdHJpbmcgfCBudWxsID0gbnVsbDtcblxuICBxdWVyeSA9IG5ldyBBcG9sbG9RdWVyeUNvbnRyb2xsZXIodGhpcywgUGFnZUJ5SWREb2N1bWVudCwge1xuICAgIG5vQXV0b1N1YnNjcmliZTogdHJ1ZVxuICB9KTtcblxuICB1cGRhdGUoY2hhbmdlZDogUHJvcGVydHlWYWx1ZXM8dGhpcz4pOiB2b2lkIHtcbiAgICBpZiAoY2hhbmdlZC5oYXMoJ3BhZ2VJZCcpKSB7XG4gICAgICBjb25zdCB7IHBhZ2VJZCB9ID0gdGhpcztcbiAgICAgIGlmIChwYWdlSWQpIHtcbiAgICAgICAgdGhpcy5xdWVyeS52YXJpYWJsZXMgPSB7IGlkOiB0aGlzLnBhZ2VJZCB9O1xuICAgICAgICB0aGlzLnF1ZXJ5LnN1YnNjcmliZSgpO1xuICAgICAgfVxuICAgIH1cbiAgICBzdXBlci51cGRhdGUoY2hhbmdlZCk7XG4gIH1cbiAgXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgICAgPGxhYmVsPlxuICAgICAgICAgIFBhZ2VJRFxuICAgICAgICAgIDxpbnB1dCBAY2hhbmdlPVwiJHtlID0-IHRoaXMucGFnZUlkID0gZS50YXJnZXQudmFsdWV9XCIvPlxuICAgICAgICA8L2xhYmVsPmA7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8YXBvbGxvLWNsaWVudCB1cmk9XCJodHRwczovL2FwaS5zcGFjZXgubGFuZC9ncmFwaHFsXCI-XG4gICAgPHNpbXBsZS1ncmVldGluZyBuYW1lPVwiV29ybGRcIj48L3NpbXBsZS1ncmVldGluZz5cbiAgPC9hcG9sbG8tY2xpZW50PlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

```ts

@customElement("app-page")
export class AppPage extends LitElement {
  @property() pageId: string | null = null;

  query = new ApolloQueryController(this, PageByIdDocument, {
    noAutoSubscribe: true
  });

  update(changed: PropertyValues<this>): void {
    if (changed.has('pageId')) {
      const { pageId } = this;
      if (pageId) {
        this.query.variables = { id: this.pageId };
        this.query.subscribe();
      }
    }
    super.update(changed);
  }
}
```

See this page for more examples of how to validate variables before fetching

https://apolloelements.dev/guides/cool-tricks/validating-variables/

**Comment by justinfagnani** [comment]
We're figuring out how to fix the error on our end, but I think there's also a API design issue here with ApolloQueryController because the query variables are given as an object not as a callback.

I think we should assume that query variables may be based on host state and should be allowed to be fully dynamic by default. A host may update at any time, in this case the `pageId` could change as a result of an attribute or binding change.

And since variables may change and become invalid dynamically too, `canQuery()` would let the host control when new queries are issued.

So instead of:

```ts
@customElement("app-page")
export class AppPage extends LitElement {
  @property() pageId: string | null = null;

  query: ApolloQueryController<PageByIdQuery, PageByIdQueryVariables> | null = null;

  firstUpdated(): void {
    if (this.pageId !== null) {
      this.query = new ApolloQueryController(this, PageByIdDocument, {
        variables: {
          id: this.pageId,
        },
      });
    }
  }

  render() {}
}
```

You would have a callback for variables that's checked in `hostUpdate`:

```ts
@customElement("app-page")
export class AppPage extends LitElement {
  @property() pageId: string | null = null;

  query = new ApolloQueryController(this, PageByIdDocument, {
    variables: () => ({
      id: this.pageId,
    }),
    canQuery: () => this.pageId !== undefined,
  });
    
  render() {}
}
```

**Comment by LasseRosenow** [comment]
@bennypowers Would be amazing if Apollo elements would implement the API change that @justinfagnani proposed, as this would make writing queries that have variables that change over time or are properties of the component soo much more easy :)

It's almost like magic 😅

**Comment by bennypowers** [comment]
Can you try again with latest?

**Comment by LasseRosenow** [comment]
I updated to 2.0.1 and now I get this error:

```
chunk-7YGAR6KA.js?v=0678c0fe:3 Uncaught TypeError: Cannot read from private field
    at __accessCheck (chunk-7YGAR6KA.js?v=0678c0fe:3:11)
    at __privateGet (chunk-7YGAR6KA.js?v=0678c0fe:6:3)
    at ApolloQueryController.hostConnected (apollo-query-controller.ts:109:9)
    at AppPageById.addController (reactive-element.ts:867:31)
    at new ApolloController (apollo-controller.ts:154:5)
    at new ApolloQueryController (apollo-query-controller.ts:102:5)
    at app-page-by-id.ts:34:24
```

Bug I still think that it changing the variable argument to a function and making the controller responsive to changes in the host state would be a much better solution overall. Because this would make the code so much cleaner and in general easier to handle

**Comment by bennypowers** [comment]
That's odd, 2.0.1 doesn't use `__privateGet`

https://unpkg.com/browse/@apollo-elements/core@2.0.1/apollo-query-controller.js

**Comment by LasseRosenow** [comment]
I think __privateGet is something esbuild does

**Comment by bennypowers** [comment]
what happens if you set `target: "es2022"` in tsconfig (ts 4.6+)?

**Comment by LasseRosenow** [comment]
its still the same it seems, but I use esBuild so I think the typescript compiler (ts 4.6) is not even getting used right now in the dev server

**Comment by bennypowers** [comment]
I'm going to close this for now since there are idiomatic workarounds e.g. https://github.com/bennypowers/lazy-query-example

I can consider the API change @justinfagnani suggested, but I am reticent to make more changes which diverge from the [apollo client APIs](https://www.apollographql.com/docs/react/api/react/hooks/#params) (see also #203)

If that's something you feel strongly about, feel free to open another issue from the above example comment

**Comment by justinfagnani** [comment]
@bennypowers that Apollo client API is necessarily different because the hook invocation runs every render, while a controller setup runs once. So if you want the controller to react to host changes it needs a callback to call in it's own `hostUpdate()`.
