### ISSUE TITLE
Not able to configure Apollo Elements

### ISSUE THREAD

**Issue by nsisodiya** [apollo-elements/apollo-elements#245]
I have tried a few times but have not been able to set up ApolloElements with a Lit-HTML setup. Belive me, getting started is very confusing.

Also, how to get rid of `React`?
```
ERROR in ../../node_modules/@apollo/client/react/context/ApolloConsumer.js 2:0-31
Module not found: Error: Can't resolve 'react' in '/Users/narendrasisodiya/Coding/yugam-tech/experiement/yugam/node_modules/@apollo/client/react/context'

ERROR in ../../node_modules/@apollo/client/react/context/ApolloContext.js 1:0-31
Module not found: Error: Can't resolve 'react' in '/Users/narendrasisodiya/Coding/yugam-tech/experiement/yugam/node_modules/@apollo/client/react/context'
```

**Comment by bennypowers** [comment]
Can you be more specific than that? A minimal reproduction, with expected and actual results would help me understand what is happening for you.

**Comment by bennypowers** [comment]
see https://github.com/apollographql/apollo-client/issues/7318 and https://github.com/apollographql/apollo-client/issues/8190
