### ISSUE TITLE
Playground is very confusing.

### ISSUE THREAD

**Issue by nsisodiya** [apollo-elements/apollo-elements#246]
This is what i see my browser. 
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/333455/163812623-88c13dd3-bf06-4b14-8663-4594054917d7.png">

When I click on Edit Live, it shows all the files which are hidden. like this

<img width="884" alt="image" src="https://user-images.githubusercontent.com/333455/163812777-7a754a28-98c9-4ade-8e25-18bf37d1ea13.png">

as a user, I never clicked on that button (until recently and by accient). A normal user will never figure out that there is a code available.

**Comment by bennypowers** [comment]
I'm not really sure what you mean by "showing files which are hidden".

If you have specific ui improvements to suggest, Please file them as feature requests on https://github.com/google/playground-elements/issues
