### ISSUE TITLE
@defer support

### ISSUE THREAD

**Issue by jpvajda** [apollo-elements/apollo-elements#255]
👋 

At Apollo we are currently working on implementing `@defer` support in our Web Client I wanted to check in to see if there was any questions we can answer to help this library leverage the use of `@defer` once we release it.

https://github.com/apollographql/apollo-client/issues/8184

**Comment by bennypowers** [comment]
will defer support involve any new or changed apis on `ApolloClient` and friends?

**Comment by jpvajda** [comment]
Good question @bennypowers!  @alessbell on our team is working on the implementation so I'll let her take this question.

**Comment by alessbell** [comment]
👋 @bennypowers the draft PR is open here: https://github.com/apollographql/apollo-client/pull/10018

There are no planned changes to `ApolloClient` APIs—the PR mostly involves adding support for multipart responses and merging the `result`'s `path` with existing data in `src/core/QueryInfo.ts`—but let me know if you have any other questions :)

**Comment by bennypowers** [comment]
from a cursory glance at the PR it looks like it will probably Just Work:tm:

**Comment by jpvajda** [comment]
@bennypowers That's great to hear! If anything comes up, please let us know.

**Comment by jpvajda** [comment]
👋  Just a follow up to my comment above: `@defer` is now supported in Apollo Web Client. You can see our[ docs ](https://www.apollographql.com/docs/react/data/defer)for more information.

**Comment by bennypowers** [comment]
I put together a [little demo](https://lit.dev/playground/#gist=8b4ebab61a3f75f9efd3a56755d51f19) using the spacex.land server, but that doesn't support `@defer`. Can you suggest a demo api?

**Comment by alessbell** [comment]
Hi @bennypowers 👋

I don't have a public demo API to share with you—I'm also on the lookout but haven't found any after a quick survey—but I did spin up a demo with apollo-elements + @apollo/client@3.7.0-beta.7, our latest beta release with `@defer` support.

It's running against a dockerized test graph that you can run with `npm run router:up` from inside the `[apollo-elements-demo](https://github.com/apollographql/router-defer-e2e-tests/tree/apollo-elements-demo/apollo-elements-demo)` folder (requires docker and docker-compose).

Sorry for the grainy gif, but it's working nicely! Feel free to close this issue out and/or let me know if I can answer any other questions about defer support in Apollo Client :)

![CleanShot 2022-09-20 at 11 24 37](https://user-images.githubusercontent.com/5139846/191300657-57410337-bcc7-47bc-a82a-106bc3498c2f.gif)

**Comment by bennypowers** [comment]
v cool!

thanks for the interest in this library
