### ISSUE TITLE
Safari notice about `static`

### ISSUE THREAD

**Issue by damontgomery** [apollo-elements/apollo-elements#257]
## Package
`@apollo-elements/components`

## Description
We have a Storybook project that uses Lit and ApolloClientElement.

When loading Safari, we get this notice and (maybe related or not) the component does not load.

![safari_notice](https://user-images.githubusercontent.com/397902/192832415-1e5feb3b-2031-40d4-85c6-1018d9b10213.jpg)

This is not supported in Safari: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_static_initialization_blocks.

Could this component use a method that is supported? I'm not familiar with static blocks much at all, so not sure what to recommend.

## Steps To Reproduce
Update dependencies to current version
```
    "@apollo-elements/components": "^3",
    "@apollo-elements/lit-apollo": "^5",
    "@apollo/client": "^3",
```

Run `yarn install`, `npm start`.

## Expected Behavior

- Demo site still works (it doesn't even in Chrome)
- Works in Safari and doesn't throw the error

## Screenshots
See above

## Browser and Version

- MacOS Safari 15.6.1
- MacOS Chrome Version 105.0.5195.125 (Official Build) (x86_64)

**Comment by damontgomery** [comment]
Provided updated testing notes.

The demo repo uses versions of the NPM packages that are several major versions old. I haven't looked into updating this to demonstrate the issue in more detail, but if you update the packages the loading part doesn't work in Chrome or Safari and Safari throws the error.

**Comment by damontgomery** [comment]
Does this help? https://github.com/damontgomery/apollo-elements-repro/tree/safari-issue

**Comment by bennypowers** [comment]
Should work with `@apollo-elements/components@3.0.5` 
![image](https://user-images.githubusercontent.com/1466420/193428326-a11ffec4-b0fa-41ee-9cc5-0b7945f439d0.png)

That's GNOME web aka epiphany aka webkit in the bottom left

**Comment by damontgomery** [comment]
Thanks @bennypowers! I believe that has resolved our issue!
