### ISSUE TITLE
Create generators for apollo-elements projects and components

### ISSUE THREAD

**Issue by camstuart** [apollo-elements/apollo-elements#26]
It would be great to see a polymer project with apollo-elements already set up, maybe a todo app or something?

See [below](https://github.com/apollo-elements/apollo-elements/issues/26#issuecomment-459980023)

> OK. The [open-wc](https://open-wc.org) people have some app generators we could build upon. I think we could piggyback on their generators for this project, publishing a `generator-lit-apollo` package to npm from this monorepo.
> 
> https://open-wc.org/developing/generator.html#available-scaffold-generators
>
> @daKmoR's suggestion was something like:
> 
> ```
> yo lit-apollo:app
> # which internally runs
> yo open-wc:scaffold-vanilla
> # some extra apollo stuff
> ```
> PRs welcome.

**Comment by bennypowers** [comment]
https://lit-apollo-subscriptions.herokuapp.com

https://gitlab.com/bennyp/demo-lit-apollo-subscriptions

This is in the README, but maybe it was not noticeable. Where would you expect that in a README? Should I put it further up?

**Comment by bennypowers** [comment]
Would you be interested in a project generator for lit-apollo?

**Comment by camstuart** [comment]
@bennypowers would l ever!!

**Comment by camstuart** [comment]
Not sure how I missed your demo?? Often I see things like this toward the top of the readme... But it's late and I've been coding all afternoon/evening so there's a strong chance I just missed it

**Comment by abdonrd** [comment]
I would like to see a PR/branch on the PWA Starter Kit! Like the other PWA Starter Kit templates.

**Comment by bennypowers** [comment]
OK. The [open-wc](https://open-wc.org) people have some app generators we could build upon. I think we could piggyback on their generators for this project, publishing a `generator-lit-apollo` package to npm from this monorepo.

https://open-wc.org/developing/generator.html#available-scaffold-generators

@dakmor's suggestion was something like:

```
yo lit-apollo:app

# which internally runs
yo open-wc:scaffold-vanilla
# some extra apollo stuff
```

PRs welcome.

**Comment by bennypowers** [comment]
This commit makes the demo much more visible in the README https://github.com/apollo-elements/apollo-elements/commit/8ed53802e9a4ee142731d75e6155927e8859bf29

**Comment by TimPietrusky** [comment]
@bennypowers Would be awesome to also make the demo much more visible on https://github.com/apollo-elements/apollo-elements/tree/master/packages/lit-apollo, because that is the only README I'm looking at right now, because I'm only interested in lit-apollo.

**Comment by bennypowers** [comment]
@TimPietrusky done
