### ISSUE TITLE
Polymer <apollo-query> Results not updating when setting variables

### ISSUE THREAD

**Issue by taniamhn** [apollo-elements/apollo-elements#27]
I'm using apollo-query to refetch a query with the same variables but the result is not updating. I notice  that your using setVariables to refetch the query but in the apollo client [documentation](https://www.apollographql.com/docs/react/api/apollo-client.html#ObservableQuery.setVariables) says that the method is use for internal use only and instead you should use refetch. I made the change locally and it works as expected.

**Comment by bennypowers** [comment]
Sounds good. Would you like to make a PR?

**Comment by bennypowers** [comment]
Are you using the polymer package?

**Comment by taniamhn** [comment]
Yes I'm using the polymer package. This is how I'm using apollo-query in my component. I'm just showing the relevant parts for you to have an idea of how I'm using it.

```
static get template() {
   return html`
      <apollo-query query="[[query]]" variables="[[_setVariables(date)]]" data="{{result}}"></apollo-query>
      <vaadin-date-picker value="{{date}}"></vaadin-date-picker>
   `
}

constructor() {
   super();
   this.query = gql`
      query dayAppointments($date: Date!) {
         appointments(start: $date) {
            ...
         }
      }
   `
}

_setVariables(date) {
   return date ? { date } : {};
}
```

**Comment by bennypowers** [comment]
If the variables are equivalent, ObservableQuery won't refetch.

[0.0.6](https://github.com/apollo-elements/apollo-elements/releases/tag/%40apollo-elements%2Fpolymer%400.0.6) exposes the `refetch` method, which will let you imperatively force a fetch, even with equivalent variables.
