### ISSUE TITLE
Update docs to highlight local state

### ISSUE THREAD

**Issue by AndreasGalster** [apollo-elements/apollo-elements#31]
Now that state management has shipped in the core of apollo client, do you think you'll make changes to the library or add some recipes on how to handle global state management? 

E. g. I fetch some data from a view component and want to subscribe to the data via all the child components without having to data-bind everywhere, instead, I can refer to the data in the global store.

**Comment by bennypowers** [comment]
You can already do this with client v2.4 and `apollo-link-state`. I'm planning to review the changes in client 2.5 in depth soon. It will likely be a minor version

**Comment by bennypowers** [comment]
AFAICT this works out of the box with current-version apollo-elements.

It would be worth updating the docs to reflect the new reality.
