### ISSUE TITLE
Support for Stencil

### ISSUE THREAD

**Issue by davidleger95** [apollo-elements/apollo-elements#36]
I work with Stencil and would like to see a version of apollo-elements made for/with Stencil components.

I tried briefly to make my own using this project as a starting point but couldn't quite get it to work. The decorators used by Stencil seemed to get in the way so I wasn't able to use approaches from some of the other libraries/frameworks that are supported. Perhaps that's why there isn't a Stencil version here yet?

I'm hoping that maybe other people are looking for Stencil apollo-elements and we'll be able to build something that works.

**Comment by bennypowers** [comment]
That's a great idea. Perhaps we can take your own as a starting point?

Have you tried the class mixins?

**Comment by FluorescentHallucinogen** [comment]
@davidleger95 PTAL at:

* https://medium.com/the-guild/stencil-apollo-stencil-meets-graphql-6fec577ee615
* https://github.com/ardatan/stencil-apollo

* https://graphql-code-generator.com/docs/plugins/typescript-stencil-apollo

The best part of web components is interoperability. This means that you can use web components written e.g. using LitElement in the projects written e.g. in Stencil, and vice versa. Also web components are interoperable with frameworks.

See:

* https://custom-elements-everywhere.com
* https://robdodson.me/interoperable-custom-elements/

The best part of `apollo-elements` is that you don’t have to use custom elements at all (there are some interop issues in React in how it passes data to custom elements and how it listen for DOM events coming from custom elements), you can use [class mixins](https://github.com/apollo-elements/apollo-elements/tree/master/packages/mixins).

Feel free to share more details about interop issues between `apollo-elements` and Stencil that you are faced, if there are any.

**Comment by davidleger95** [comment]
@bennypowers hey, sorry for the late reply. We're a little far away (at least a month or 2) from focusing on GraphQL in our project right now. So this isn't currently a priority, but when we eventually get to needing GraphQL in Stencil we will circle back.

In terms of the starting point I had, I didn't make any worthwhile progress. Just a lot of trial, with mostly error so far.

---

@FluorescentHallucinogen Interesting! This looks helpful. I'll check it out for sure, thanks! And yes, I'll share my experiences if relevant.

To the point of web components being able to be used anywhere: Yes, you are correct. My main concern however is with loading an additional WC library for just a few components. Or is there something I'm missing which would make that assumption wrong?

**Comment by bennypowers** [comment]
@davidleger95 any updates here?

**Comment by bennypowers** [comment]
I'd love to see this land for Hacktoberfest

Ideally, stencil support should reuse logic from `@apollo-elements/mixins`, while only adding stencil-specific annotations to the base classes.

**Comment by bennypowers** [comment]
I have no plans to do this at the moment, so closing. Happy to take a PR though
