### ISSUE TITLE
Refetch data when variables change & use cache

### ISSUE THREAD

**Issue by llezhava** [apollo-elements/apollo-elements#39]
This issue is related to lit-apollo.
I have apolloQuery component, which uses variables.

Those variables are passed down as props from the parent component, and I want to refetch data from the server when new props arrive & use cache.

I tried the following approaches:
1) this.variables = {new variables}
2) this.refetch({new variables})
3) this.executeQuery({new variables})

My issues is the following:

1) this.variables approach is buggy. I think, it is related to this issue:
https://github.com/apollographql/react-apollo/issues/2202

2) this.refetch works, but does not use cache

3) this.executeQuery works, uses cache but does not pass down to render anything except data. so In order to make it work I have to do something like this:
```
      this.loading = true;
        let result = await this.executeQuery({
          variables: {
            from: this.from,
            categories: this.filters.categories,
            sortBy: this.filters.sortBy
          }
        });
        if (result === undefined) {
          this.loading = false;
          this.error = true;
        } else {
          this.loading = result.loading;
        }
```

**Comment by bennypowers** [comment]
Is your query using `@export` directive?

**Comment by llezhava** [comment]
> Is your query using `@export` directive?

Nope

**Comment by bennypowers** [comment]
Can you put together a repro on stackblitz? you can take this as a starting point:

https://stackblitz.com/edit/apollo-client-local-state-export-repro

**Comment by llezhava** [comment]
https://stackblitz.com/edit/apollo-client-local-state-export-repro-jrk2rw

**Comment by bennypowers** [comment]
Thanks for this issue.

The [variables setter in the apollo query class](https://github.com/apollo-elements/apollo-elements/blob/master/packages/mixins/apollo-query-mixin.js#L45) doesn't cause fetches if a query observable already exists. I suggest calling `this.subscribe()` whenever you set the variables.

For example, if your query relies on the component's `input` property, use LitElement's `updated` callback 

```js
static properties = {
  input: { type: String }
};

updated(changedProps) {
  if (changedProps.has('input')) {
    this.variables = { input: this.input }
    this.subscribe();
  }
}
```

We might change this behaviour in a future breaking change, but I don't have any specific plans for that at the moment. You are welcome to make a proposal, please open another issue or PR if you have an idea in mind.

I'll close this now, feel free to reopen if this doesn't solve your problem.
