### ISSUE TITLE
Move to GitLab

### ISSUE THREAD

**Issue by bennypowers** [apollo-elements/apollo-elements#4]
This repo will be moving to GitLab some time this month. Heads up

**Comment by FluorescentHallucinogen** [comment]
@bennypowers Because M$? ))

**Comment by bennypowers** [comment]
Honestly, because GitLab. I've been a user for years. Last few months I've been doing more on github out of convenience (webcomponents.org, npm, bower assume you're using GH) and a misguided attempt to increase my exposure. #movetogitlab gave me encouragement to commit (pun!) to gitlab again.

**Comment by LasaleFamine** [comment]
I think you should consider to stay here on GitHub. 
Although I don't like M$ and its acquisition, I think this is the place for open source projects. GitHub give open source projects much more visibility than other Git providers and this is fundamental for getting help from other developers. 

I think I wouldn't find it if it wasn't on GitHub by the way 😄 

PS: I love GitLab and I constantly use it for my personal/private projects.

**Comment by camstuart** [comment]
I'm a huge fan of GitLab. The CI is amazing and in general, it is a superior product.
Another option you might consider is to mirror the GitHub repo over in GitLab (I have some repo's set up like this)

If you want a hand let me know

**Comment by bennypowers** [comment]
@camstuart Hey, welcome 😄 

I had thought about maybe moving the project to gitlab for the ci and the management, and mirroring it here on github.

Can I set up issue hooks both ways, so that issues (and comments, and MRs) would be mirrored both ways?

**Comment by camstuart** [comment]
@bennypowers good questions indeed.

You can mirror in both directions, but I didn't see any specific details about issues and merge requests. I just had a quick look here:

https://docs.gitlab.com/ee/workflow/repository_mirroring.html

Perhaps we can set up a repo on both and give it a try. Can't hurt right?

**Comment by bennypowers** [comment]
I'm sorry to say that it doesn't seem moving to GitLab is realistic for the time being. Hopefully that will change soon. Until then I'll be closing this issue.
