### ISSUE TITLE
ApolloQuery should have `onCompleted` and `onError` Methods

### ISSUE THREAD

**Issue by AndreasGalster** [apollo-elements/apollo-elements#42]
I have a component that doesn't throw any error when I'm querying, so there's no way to figure out what's wrong with the query. When I replace the query with some other query, it works just fine. 

So since render never gets called and no error is thrown there is no way to figure out what's actually wrong with the query.

For reference: A query like this works:

```
query getRouteDetails {
    getRouteDetails @client {
        routePath 
        routeParam
    }
}
```

Something like this doesn't:

```
query getAuthor($humanId: String) {
    getAuthor(humanId: $humanId) {
        _id
        humanId
        firstName
        lastName
    }
}
```

I'm passing the variable in the constructor of the component. Any idea how to troubleshoot this? Can I somehow get error logs on what's happening before the call to render?

**Comment by bennypowers** [comment]
what happens when you add
```js
shouldUpdate() {
  return true
}
```

**Comment by AndreasGalster** [comment]
I figured out there's was an issue with the backend. That's why the client side query worked.

Still I think it would be good to have some error logging that's not dependent on the render call.

**Comment by bennypowers** [comment]
the mutation mixin has a [pair of 'abstract' methods which are called when the mutation resolves](https://apolloelements.dev/mixins/#/mixins/ApolloMutationMixin#methods). perhaps something like that for query? IN any case, you can check the error property, which will be set, although perhaps not updated. if you wanted to say, fire an error event you could do something like this:

```js
shouldUpdate() { return true }
updated(changed) {
  const error = changed.get('error')
  if (error) this.dispatchEvent(new ErrorEvent('apollo-error', { error }))
}
```

**Comment by AndreasGalster** [comment]
The onCompleted / onError methods would certainly be helpful. I was actually looking for that in the docs for the query component

**Comment by bennypowers** [comment]
PRs welcome :D

Please follow the commit convention. use `npx git-cz`
