### ISSUE TITLE
Suggestion how to handle variables for a query in a component that depends on another GraphQL store detail

### ISSUE THREAD

**Issue by AndreasGalster** [apollo-elements/apollo-elements#43]
Hi Benny, perhaps you have a suggestion how to handle the following scenario:

I have a component which fetches something like a book author and I determine which book author to load based on the route. e. g. the route may be:

domain.com/authors/darren-hardy

This gets pushed into the GraphQL client store as `routePath: '/authors'` & `routeDetail: 'darren-hardy'`

When I'm on my component and want to fetch the author "darren-hardy" I need to first get the route data from the GraphQL store before I can set the variable to set this in my component.

There's a few solutions here:

1. Just push the route data in e. g. localStorage so I can easily retrieve it but then I'm not using GraphQL store for entire store management, which is the entire point of GraphQL store management
2. Do something in the constructor like run a vanilla apolloclient query for the routeData in the store and await for that data before setting the variable in the constructor.
3. Anything else I'm missing?

Do you think solution number two makes sense or is there another way how you handle this for your own projects?

/edit:

**Nevermind number 2 wouldn't work, since you can't do an async call in a constructor.**

I tried not setting the variable in the constructor and just call a method in the constructor that initiates the retrieval of the graphQL store and then set the variable but that results in an infinite loop.

/edit:

Actually nevermind, so it does work if you create a method that initializes the call to the store and then set the variable. I just accidentally called the method setVariables which was already a reserved name in ApolloQuery.

However, if one does it that way, the component will still try to fetch first even without an initial variable set, so in my case it'll still fetch something (my mongoose query will return the first document if there's no variable set)

So basically, first fetch & render update is the fetch without a variable set, the second fetch & render update will be with the proper variable set.

/edit:

I suppose one could check for this.variables in the render call and then render nothing if no variables are defined.

```
    if(!this.variables) {
      return nothing;
    }
```

This would still result in two queries being executed though, which could be a problem for heavier ones.

I'm just trying to figure out what's the best way to do this with the least amount of boilerplate necessary to keep things DRY. **Food for thought:** Should a component that requires variables fetch & render if no variables are set?

So while what I came up with works, it runs queries twice and it requires a lot of non-DRY setup. This is Ok for one component but if I have 6 different components on the page that all need to get the route state from the GraphQL store, that's a bit frustrating.

So this is what I have in my constructor right now FYI:

![image](https://user-images.githubusercontent.com/3836411/55600049-0fe23900-578d-11e9-8c9d-1f89bffccae1.png)

**Comment by bennypowers** [comment]
Sounds like you need to export your client variables:

```graphql
query GetAuthor($humanId: String!) {
  routePath @client
  routeDetail @client @export(as: "humanId")
  author(humanId: $humanId) {
    foo
    bar
    baz
  }
}
```

That *should* work out of the box, however there is a nasty [bug in apollo-client](https://github.com/apollographql/apollo-client/issues/4530#issuecomment-480024441) so you'll need to use this workaround for now:

```js
/** @inheritdoc */
updated(changed) {
  const newData = changed.get('data');
  if (!newData || !this.data) return;
  // You'll need to do this for all exported variables.
  if (newData.humanId !== this.data.humanId) this.subscribe();
}
```

**Comment by AndreasGalster** [comment]
Thanks wasn't aware of this syntax, learned something new. Will try it tomorrow 🙏

**Comment by bennypowers** [comment]
It's a new feature in apollo-client 2.5

**Comment by bennypowers** [comment]
Closing for now, if you still need help, please reopen

**Comment by bennypowers** [comment]
Keep in mind, apollo-client 2.6 fixes the bug with `@export` so you don't need to hack around in `updated`
