### ISSUE TITLE
[lit-apollo] Clarify "Usage" in README

### ISSUE THREAD

**Issue by TimPietrusky** [apollo-elements/apollo-elements#45]
I tried to understand the [Usage](https://github.com/apollo-elements/apollo-elements/tree/master/packages/lit-apollo#-usage) part a few times now and also after digging into the src of apollo-elements and the leeway demo, I still don't understand everything.

```js
import { ApolloClient } from 'apollo-client';
import { ApolloQuery, html } from '@apollo-elements/lit-apollo';
import { cache } from './cache';
import { link } from './link';

// Create the Apollo Client
const client = new ApolloClient({ cache, link });
```

* What is the connection between `ApolloQuery` & `client`? Like how does ApolloQuery know that it should that particular client? Is it because I set `this.client` in the constructor?
* Where is `./cache` & `./link` coming from? I guess this is implicit knowledge if you have used GraphQL with Apollo before, but my background is that I started GraphQL in Java (there is no Apollo) and then wanted to use GraphQL with LitElement and found this repo. 

```js
          <connected-child id="child-component"
              .client="${this.client}"
              .query="${childQuery}"
          ></connected-child>`
```

* What is the `connected-child`? Is this also extending ApolloQuery?  
* Do I also have to set a property named `client` on my class to get the relation between `client` and `ApolloQuery`?

All of this I can answer the longer I look at the Usage, but it would be super nice to have a proper documentation that describes how this works instead of having "just" an example that (from my point of view) is not complete if you are a beginner and have never used anything from Apollo. 

Maybe it would make sense to also link a tutorial to ApolloClient? And add a comment into the constructor?

**Comment by TimPietrusky** [comment]
I just found https://apolloelements.dev/lit-apollo/#/classes/ApolloQuery, which is super helpful and should be added to the README of lit-apollo too.

**Comment by bennypowers** [comment]
Those are great suggestions and I agree the documentation should be improved. PR's are surely welcome. Thanks for the issue.

**Comment by kevinsimper** [comment]
That there is no link to `./cache` & `./link` is just making this super confusing, I normally go to Webcomponents for a simpler approach and this made me more confused and the demo is super complex as well 😅

**Comment by bennypowers** [comment]
Thanks @kevinsimper for the notes. Not to kick the can but in our case, the majority of the DX complexity comes from apollo. Luckily for us, apollo-client 2.6.0 just landed which hopefully will provide some niceties for developers that want to bundle it. God-willing, I'll soon have some time to review the README and improve it.

**Comment by TimPietrusky** [comment]
Thank you very much, this looks super good now!

**Comment by teamgroove** [comment]
I'm still don't unterstand that part:
 <connected-child id="child-component"
              .client="${this.client}"
              .query="${childQuery}"
          ></connected-child>`

**Comment by bennypowers** [comment]
@teamgroove 

In that example, we are binding the ApolloClient instance down to the child component.

If in the first place, we assign the client to `window.__APOLLO_CLIENT__`, then it will not be necessary to explicitly bind it, which Is what I prefer.

The point of showing an example of explicitly binding is for someone who, for whatever reason, doesn't want to assign it to a global variable.

☝️ all that, it seems, should be added to the docs.

As for the query, just like we can bind a GraphQL query document in a class field, or in the constructor, you can also set it as a property on a component instance. This might be useful if you have a variety of queries which all share a common response schema, and you want to write a common display component for them:

```js
html`
  <response-element .query="${catsQuery}"></response-element>
  <response-element .query="${dogsQuery}"></response-element>
  <response-element .query="${ayeayesQuery}"></response-element>
`
```

This, too, should be made explicit in docs.

I really appreciate your coming here to give your feedback. I'll reopen this issue until those points are resolved.
