### ISSUE TITLE
Upgrade to the released lit-element package

### ISSUE THREAD

**Issue by justinfagnani** [apollo-elements/apollo-elements#47]
The `@polymer/lit-element` npm package has been moved to `lit-element`. `@polymer/lit-element` is deprecated and not receiving any updates, so please upgrade to `lit-element@^2.0.0` as soon as possible.

Thanks!

**Comment by bennypowers** [comment]
[`lit-apollo`](https://npm.im/lit-apollo) package (deprecated) uses `@polymer/lit-element`, but the current package  [`@apollo-elements/lit-apollo`](https://npm.im/@apollo-elements/lit-apollo) uses `lit-element` instead.

https://github.com/apollo-elements/apollo-elements/blob/36a6a137c69795087edb47cb780008f4a43b06ee/packages/lit-apollo/package.json#L37
