### ISSUE TITLE
”defaultOptions” option is not working on ApolloClient

### ISSUE THREAD

**Issue by NickPappagiorgio** [apollo-elements/apollo-elements#48]
## Description
I tried to use the **"defaultOptions"** option on ApolloClient, I set it up like this,

```javascript
const defaultOptions = {
  watchQuery: {
    fetchPolicy: 'cache-and-network'
  },
  query: {
    fetchPolicy: 'cache-and-network'
  }
}


client = new ApolloClient({
    cache,
    link,
    defaultOptions
  })
```

but I didn't feel any effect on doing it.

In order to make it work, I had to set the **`fetchPolicy`** property to **`'cache-and-network'`** when using ApolloQuery.

Can you explain how to set it up properly to get it to work?

**Comment by bennypowers** [comment]
Hi @NickPappagiorgio Thanks for the issue 👋 

Can you demonstrate that this is an apollo-elements issue, instead of an apollo-client issue?
Are you using apollo-client 2.6.0?
Do you have a reproduction (glitch or stackblitz, etc)?

**Comment by NickPappagiorgio** [comment]
Hi @bennypowers 👋

As I dug deeper in this rabbit hole I found out that the problem is with **apollo-client** rather than apollo-elements. I found a related [issue](https://github.com/apollographql/apollo-client/issues/2555), it's opened since Nov. 2017.

Besides that, yes I'm using _apollo-client 2.6.0_
