### ISSUE TITLE
No matching version found for @apollo-elements/mixins@^1.0.1

### ISSUE THREAD

**Issue by kevinsimper** [apollo-elements/apollo-elements#50]
$ npm i -S @apollo-elements/lit-apollo

and correct enough it doesn't exist

https://www.npmjs.com/package/@apollo-elements/mixins

**Comment by bennypowers** [comment]
Thank you *very* much for the report. Lerna is the joy of my life.

I manually published the packages, please try `@apollo-elements/lit-apollo@1.0.3` and let me know.

**Comment by kevinsimper** [comment]
Yes that works, haha, glad you fixed it 👍
