### ISSUE TITLE
Rerender when script application/graphql change

### ISSUE THREAD

**Issue by kevinsimper** [apollo-elements/apollo-elements#51]
I can see now that the Readme for ApolloQuery doesn't show the `<script type="application/graphql">` at the top of the README, but still does in the `apollo-elements` root README.

Is that intentional?

I noticed that the lit-apollo element doesn't rerender when `<script type="application/graphql">` changes, and the README for `apollo-query` now says that. I didn't notice that before.

I don't know why it should refetch if it receives new props.

If you loop over an array and then sort it, the elements will show the value for the old row and not the new row.

Say it looks like this at the start
```
1 <apolloquery>true <a href="1"></a></apolloquery>
2 <apolloquery>false <a href="2"></a></apolloquery>
3 <apolloquery>false <a href="3"></a></apolloquery>
```
then apollo query will fetch that data. Then you sort it
```
3 <apolloquery>true <a href="3"></a></apolloquery>
2 <apolloquery>false <a href="2"></a></apolloquery>
1 <apolloquery>false <a href="1"></a></apolloquery>
```
That is not that easy to figure out at first that it is apollo-query that doesn't refetch and not you who made a render mistake. Because the number is correct, the field will say 3 because you pass it as parameters, so lit-element will rerender the `render()` function. See how the link href updates, but the value stays the same.

Apollo-query: 1.1.0

**Comment by bennypowers** [comment]
> I noticed that the lit-apollo element doesn't rerender when <script type="application/graphql"> changes

I want to understand what you mean here. Do you mean that apollo client doesn't fetch the new query when you remove the `<script type="application/graphql">` child and then append a new script child?

> I don't know why it should refetch if it receives new props.

Is this referring to query variables, or lit-element observed properties? Do you mean you think that the query should refetch whenever any observed element properties change? 

> If you loop over an array and then sort it, the elements will show the value for the old row and not the new row. [example]

Where is this array coming from? Is it provided by the apollo cache? is it an observed property separate from the element's `data` property? is it destructured off that `data` property? Are you rendering `<apollo-query><script type="application/graphql"></script></apollo-query>` for each member of the array? Are you using `@apollo-elements/polymer` or `@apollo-elements/lit-apollo`?

**Comment by kevinsimper** [comment]
> I want to understand what you mean here. Do you mean that apollo client doesn't fetch the new query when you remove the `<script type="application/graphql">` child and then append a new script child?

The bug in my app happened when lit-element would update the child directly, therefore no new script is append, the variables is updated inside the string.

> Is this referring to query variables, or lit-element observed properties? Do you mean you think that the query should refetch whenever any observed element properties change?

I think it should refetch if a prop change. As lit-element updates the DOM intelligently, it doesn't empty the container before inserting the dom nodes. If it did then it would automatically rerender. Because lit-element just updates the placeholders in the DOM elements, the props change and rerenders, but the data is from the previous props, often from a different element in the array order.


> Where is this array coming from? Is it provided by the apollo cache? is it an observed property separate from the element's `data` property? is it destructured off that `data` property? Are you rendering `<apollo-query><script type="application/graphql"></script></apollo-query>` for each member of the array? Are you using `@apollo-elements/polymer` or `@apollo-elements/lit-apollo`?

The array is coming from another rest API, it is a observ prop in a lit-element.

---

I think apollo-elements is a really cool to migrate bigger applications a component at a time 😄I really appreciate all the work, this project is again really great!

**Comment by bennypowers** [comment]
> The bug in my app happened when lit-element would update the child directly, therefore no new script is append, the variables is updated inside the string.

This shouldn't trigger an update. Instead, you should pass the variables as the `variables` property of the element, and keep the graphql document static.

```html
<my-element id="el">
  <script type="application/graphql">
    query Stuff($things: String) {
      stuff(things: $things)
    }
  </script>
</my-element>

<input id="input"/>

<script>
  const input = document.getElementById('input');
  const el = document.getElementById('el');
  input.oninput = function() {
    el.variables = { things: this.value };
    el.subscribe();
  }
</script>
```

But if you're anyways using a DOM-in-JS lib like lit-html, it might make more sense to pass the query as an object rather than as DOM

```js
import { ApolloQuery, html } from '@apollo-element/lit-apollo';
// use rollup-plugin-graphql or graphql/loader
import QUERY from './my-el.graphql';

customElements.define('my-el', class MyEl extends ApolloQuery {
  query = QUERY;
  /* ... */
});
```

> I think it should refetch if a prop change.

I think you're talking about updating the `variables` property. [Currently, that won't resubscribe](https://github.com/apollo-elements/apollo-elements/blob/bcb43d50f48e814f36dcca260e896beb234983ac/packages/mixins/apollo-query-mixin.js#L101), so you have to manually do it, as above. This behaviour, by the way, is cribbed from the `react-apollo` impl.

> The array is coming from another rest API, it is a observ prop in a lit-element.

So I might do something like this:

```js
class MyEl extends ApolloQuery {
  @property({ type: Array }) restResponse = [];
  updated(changed) {
    if (changed.has('restResponse')) {
      this.variables = { ...this.variables, things: this.restResponse }
      this.subscribe()
    }
  }
}
```

> I think apollo-elements is a really cool to migrate bigger applications a component at a time 😄I really appreciate all the work, this project is again really great!

You're too sweet. Thank you! ❤️

**Comment by kevinsimper** [comment]
That clears up a lot about the API 👍Thank you a lot!

**Comment by bennypowers** [comment]
I'm adding the Documentation label here because this issue exposes a lack in the usage docs.

I'm going to close now because it seems I've addressed your issue. Please re-open if I'm mistaken about that.
