### ISSUE TITLE
loading is always false

### ISSUE THREAD

**Issue by kevinsimper** [apollo-elements/apollo-elements#52]
I spent some time creating a reproducible example
https://codesandbox.io/s/stoic-noether-d47ts

You can see in the console that it always says false, the loading state is never true and therefore loading is never showed to the user.

**Comment by bennypowers** [comment]
This is an apollo-client issue. The hoop you have to jump through to get that sweet, sweet `loading` state is to set your fetchPolicy

Put this in your class body:
```js
fetchPolicy = 'cache-and-network'
```
or instantiate your client like so:

```js
new ApolloClient({ cache, link, defaultOptions: {
  watchQuery: {
    fetchPolicy: 'cache-and-network',
    errorPolicy: 'ignore',
  }
})
```

https://codesandbox.io/s/epic-rhodes-djplf

Feel free to reopen if this doesn't address your issue.
