### ISSUE TITLE
Remove Default Fetch Policy

### ISSUE THREAD

**Issue by bennypowers** [apollo-elements/apollo-elements#53]
[`mixins` sets a default `fetchPolicy`](https://github.com/apollo-elements/apollo-elements/blob/196d9529b84e2b0c34f7c74264a03279f5f8dad2/packages/mixins/apollo-subscription-mixin.js#L56) on a [per-component basis](https://github.com/apollo-elements/apollo-elements/blob/196d9529b84e2b0c34f7c74264a03279f5f8dad2/packages/mixins/apollo-subscription-mixin.test.js#L34). This may conflict with the user's [default options](https://www.apollographql.com/docs/react/api/apollo-client/)

The choice of default fetch policy should therefore be deferred to ApolloClient, this setting should be removed.

https://glitch.com/edit/#!/brassy-philosophy?path=script.js:14:3

**Comment by kevinsimper** [comment]
Is this related to #52 

I got this working locally but only by changing it inside the component and not the client :)

**Comment by bennypowers** [comment]
Yes that's exactly the bug. Currently element instances always override the clients defaults.

**Comment by bennypowers** [comment]
This was merged into v2 branch, which will close this issue when it lands

**Comment by bennypowers** [comment]
Closed in #68 

Sorry for the delay.

There's quite some changes in the new 2.0 version so take a look at the release notes
