### ISSUE TITLE
lit-apollo has no exported member 'html'

### ISSUE THREAD

**Issue by peschee** [apollo-elements/apollo-elements#59]
## Package

`@apollo-elements/lit-apollo`

## Description

The `@apollo-elements/lit-apollo` package has no exported member `html`.

The [usage docs](https://github.com/apollo-elements/apollo-elements/tree/master/packages/lit-apollo#-usage) state that the following `html` import should be used:

```
import { ApolloQuery, html } from '@apollo-elements/lit-apollo';
```

However, it seems that `@apollo-elements/lit-apollo` has no such exported member:

```
export { ApolloElement } from "./apollo-element";
export { ApolloQuery } from "./apollo-query";
export { ApolloMutation } from "./apollo-mutation";
export { ApolloSubscription } from "./apollo-subscription";
export { MutationResult } from "@apollo-elements/mixins/apollo-mutation-mixin";
export { OnSubscriptionDataOptions, SubscriptionResult } from "@apollo-elements/mixins/apollo-subscription-mixin";
```

## Steps To Reproduce
1. `npm install --save @apollo-elements/lit-apollo`
2. Add `import { ApolloQuery, html } from '@apollo-elements/lit-apollo';` in your component code
3. See error

## Expected Behavior

Shouldn't the docs state the following?

```
import { html } from 'lit-element';
```

**Comment by bennypowers** [comment]
which version are you using?

latest exports everything from `lit-element`

https://unpkg.com/@apollo-elements/lit-apollo@1.1.1/index.js

**Comment by peschee** [comment]
The Typescript typings are off. Here's `index.js`:

```
// Classes
export { ApolloQuery } from './apollo-query.js';
export { ApolloMutation } from './apollo-mutation.js';
export { ApolloSubscription } from './apollo-subscription.js';

// Utilities
export { render } from 'lit-html';
export * from 'lit-element';
```

and here's `index.d.ts`:

```
export { ApolloElement } from "./apollo-element";
export { ApolloQuery } from "./apollo-query";
export { ApolloMutation } from "./apollo-mutation";
export { ApolloSubscription } from "./apollo-subscription";
export { MutationResult } from "@apollo-elements/mixins/apollo-mutation-mixin";
export { OnSubscriptionDataOptions, SubscriptionResult } from "@apollo-elements/mixins/apollo-subscription-mixin";
```

**Comment by bennypowers** [comment]
There's a PR in flight to hopefully fix those typings #58

**Comment by peschee** [comment]
Allright, until then, I will resort to using `html` from `lit-element` directly.

**Comment by bennypowers** [comment]
Using this rollup.config.js, I pulled in `html` from '@apollo-elements/lit-apollo`
```js
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
export default {
  input: 'index.js',
  output: {
    file: 'build.js',
    format: 'es'
  },
  plugins: [
    resolve(),
    commonjs()
  ]
}
```

**Comment by peschee** [comment]
@bennypowers I believe you. However, using Typescript the typescript compiler throws an error because the exports in `index.d.ts` are off.

**Comment by bennypowers** [comment]
@peschee [lit-apollo@1.1.3](https://unpkg.com/@apollo-elements/lit-apollo@1.1.3/index.d.ts) is out with the fix, I hope that tides you over.
