### ISSUE TITLE
Broken import in hybrids?

### ISSUE THREAD

**Issue by darrickyee** [apollo-elements/apollo-elements#63]
## Package
`@apollo-elements/hybrids`

## Description
index.js includes the export 
`export { variablesFactory } from './factories/variables.js';`

...but the file `variables.js` does not exist.

**Comment by bennypowers** [comment]
Thank you for the report @darrickyee, the fix is now available in [@apollo-elements/hybrids@1.1.2](https://unpkg.com/@apollo-elements/hybrids@1.1.2/index.js)
