### ISSUE TITLE
Documentation Proofreading and Revision

### ISSUE THREAD

**Issue by bennypowers** [apollo-elements/apollo-elements#81]
We have lots of new docs on https://apolloelements.dev

Would love to get some :eyes: on them.

@peschee had some great feedback which I'll summarize here:

### Content and Navigation
- [x] Remove API docs footers from docs pages
- [x] Draft a main page that's not just a dump of the README
- [x] separate docs (prose) and API docs
  - consider using [rocket](https://github.com/daKmoR/rocket/) for this

### Design
- [x] light mode (`prefers-color-scheme` and toggle)
- [x] More whitespace

**Comment by ZeeshanAnwar15** [comment]
Improve docs

**Comment by bennypowers** [comment]
## Main Page

> concise intro about WHAT it is and WHICH packages it is divided into would be better

> [main page library TOC and snippets] for example, could be visually more clear and easier to navigate

Maybe the main page should break down into a table of libraries with separate links to getting started docs and api docs. This is kind of how the previous docs worked.
