### ISSUE TITLE
Question:   Will this render in IE 11?

### ISSUE THREAD

**Issue by snaplesec** [apollo-elements/apollo-elements#89]
Hi,
trying to find out if it will work in IE11, because most of everything that I have tried to use to get a graphql client integrated doesn't work.

Steve

**Comment by bennypowers** [comment]
I have no plans to support IE. I say let it die.

That being said, if you pile on transpilers and polyfills, you might be able to get it working. I wouldn't say it's impossible but it would likely take some significant creativity on your part.

**Comment by snaplesec** [comment]
I completely agree, I don’t what to deal with having to go through all of that, and maybe still won’t render.
That was what I thought it would take to make it work.

Thanks and Regards,
Steve

**Comment by bennypowers** [comment]
Thanks for stopping by. If you do manage to eke out some support, I'd be interested to know how you pull it off.

Other than that I hope you enjoy using the library in other contexts.

Best regards
