### ISSUE TITLE
[lit-apollo] TypeScript errors

### ISSUE THREAD

**Issue by Tansito** [apollo-elements/apollo-elements#99]
## Package
`@apollo-elements/lit-apollo`

## Versions
- "typescript": "~4.1.2"
- "@apollo-elements/lit-apollo": "^3.1.3",

## Description
TypeScript is showing different kind of errors for `createApolloClient` and `ApolloQuery`. They are the elements where I could see this behaviour.

## Steps To Reproduce
1. Clone this reproduction repo: https://github.com/IBM/pwa-lit-template/tree/apollo-elements
2. Just run: `npm run type-checking` or `npm run build`
3. See the errors

## Expected Behavior
No errors when passing the linter or during build time. I don't know @bennypowers if it can be related with the typescript configuration or its version.

## Screenshots
<img width="460" alt="Screen Shot 2020-12-09 at 4 34 40 PM" src="https://user-images.githubusercontent.com/9059044/101650738-952af000-3a3c-11eb-96f2-b8b6b4065dc5.png">
<img width="460" alt="Screen Shot 2020-12-09 at 4 35 17 PM" src="https://user-images.githubusercontent.com/9059044/101650758-9825e080-3a3c-11eb-96ba-001efe544eb7.png">

**Comment by bennypowers** [comment]
Hi @Tansito thanks for the report

Can you try with

```
 - @apollo-elements/components@1.3.0-alpha.1
 - @apollo-elements/fast@1.2.0-alpha.1
 - @apollo-elements/gluon@3.2.0-alpha.1
 - @apollo-elements/haunted@1.1.0-alpha.1
 - @apollo-elements/hybrids@3.4.0-alpha.1
 - @apollo-elements/interfaces@1.4.0-alpha.1
 - @apollo-elements/lib@3.5.0-alpha.1
 - @apollo-elements/lit-apollo@3.2.0-alpha.1
 - @apollo-elements/mixins@3.4.0-alpha.1
 - @apollo-elements/polymer@3.3.0-alpha.1
```

See #96  and #98

**Comment by Tansito** [comment]
Wow, quite better, 0 errors:
<img width="307" alt="Screen Shot 2020-12-09 at 5 23 37 PM" src="https://user-images.githubusercontent.com/9059044/101656848-767c2780-3a43-11eb-8c4b-976b01ee602b.png">

Let me some minutes to prepare a little test for the `ApolloQuery` too and I can confirm you if that version fix that too, thanks for your fast reply Benny!

**Comment by Tansito** [comment]
Confirmed, `ApolloQuery` is fixed too in that version. Thank you Benny!
